### ISSUE TITLE
typo in footnote 2

### ISSUE THREAD

**Issue by srayuws** [distillpub/post--td-paths#14]
Current:
the $n^{th}$ Monte Carlo update is $ V(s_t) = **V(s_{t-1})** + \frac{1}{n} \bigr[ R_{n} - V(s_t) \bigl] $ 

Should it be:
the $n^{th}$ Monte Carlo update is $ V(s_t) = **V(s_t)** + \frac{1}{n} \bigr[ R_{n} - V(s_t) \bigl] $ 
?

**Comment by greydanus** [comment]
Thanks for bringing this up...I checked with Sutton page 119 and I believe your proposed change is correct. Just submitted a change @ https://github.com/distillpub/post--td-paths/pull/15#issue-338898889
